# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'nyancat', '~> 0.2.1'

gem 'sinatra', '~> 2.2'

gem 'textstat', '~> 0.1.6'